version: "3.9"
services:
  producer:
    build: 
      context: ./producer
      dockerfile: Dockerfile
    depends_on: 
      - kafka1
      - kafka2
      - kafka3

  consumer:
    build: 
      context: ./consumer
      dockerfile: Dockerfile
    depends_on: 
      - pg
      - kafka1
      - kafka2
      - kafka3
    environment: 
      POSTGRESURI: pg

# kafka and zookeeper https://github.com/conduktor/kafka-stack-docker-compose/blob/master/zk-single-kafka-multiple.yml 

  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports: 
      - "2181:2181"
    restart: always
    environment: 
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - zoodata:/data
      - zoodatalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:6.1.0
    hostname: kafka1
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafkadata:/var/lib/kafka/data
    depends_on: 
      - zookeeper
  
  kafka2:
    image: confluentinc/cp-kafka:6.1.0
    hostname: kafka2
    ports: 
      - "9093:9093"
    environment: 
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafkadata:/var/lib/kafka/data
    depends_on: 
      - zookeeper
  
  kafka3:
    image: confluentinc/cp-kafka:6.1.0
    hostname: kafka3
    ports: 
      - "9094:9094"
    environment: 
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafkadata:/var/lib/kafka/data
    depends_on: 
      - zookeeper

  pg:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on: 
      - zookeeper

volumes: 
  db: 
  kafkadata:
  zoodata: 
  zoodatalog: 